apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: devops-demo
spec:
  replicas: 2

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: python-app

  template:
    metadata:
      labels:
        app: python-app

    spec:
      containers:
        - name: python-app

          image: YOUR_DOCKERHUB_USERNAME/devops-demo:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: DB_PATH
              value: /data/app.db

          volumeMounts:
            - name: app-data
              mountPath: /data

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 256Mi

      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data